name: Release Build clang-14

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update Repositories
      run: sudo apt update
    
    - name: Download && Install build depend
      run: sudo apt install build-essential mesa-utils
    
    - name: Download && Install clang-14
      run: sudo apt install clang-14
      
    - name: Download && Install FreeGlut
      run: sudo apt install freeglut3 freeglut3-dev
    
    - name: Download && Install Glew
      run: sudo apt install libglew-dev
    
    - name: Download && Install
      run: sudo apt install libsfml-dev

    - name: Download flashEngine
      run: git clone https://github.com/flash-cinfo/flashEngine ${{github.workspace}}/src/flashEngine

    - name: Configure Setup with Meson
      run: CC=clang CXX=clang++ meson setup ${{github.workspace}}/builddir -Dbuildtype=release

    - name: Build Flashtap
      run: cd ${{github.workspace}}/builddir && meson compile

